# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published    
jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Run tests
      run: dotnet test --configuration Release
  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ run_test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/inclus16/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out  
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./inclus16/out/*.nupkg --skip-duplicate --no-symbols true
